# Generated by Django 5.1.2 on 2024-12-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="social_provider",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
